// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlwQYae65svO7Fd-bG1ZKpaoyKgN54tY0',
    appId: '1:170898355374:web:83eb572903086f4bd9a93f',
    messagingSenderId: '170898355374',
    projectId: 'chatflutter210701',
    authDomain: 'chatflutter210701.firebaseapp.com',
    storageBucket: 'chatflutter210701.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3nCyaF1mlQchr8K3OhjlfEYa1dm-w_Mc',
    appId: '1:170898355374:android:2fa0351a38f48785d9a93f',
    messagingSenderId: '170898355374',
    projectId: 'chatflutter210701',
    storageBucket: 'chatflutter210701.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVYqt1Hh61bPIdtEbNIRBYyojoR_05UHo',
    appId: '1:170898355374:ios:5a1f3232fd40869ed9a93f',
    messagingSenderId: '170898355374',
    projectId: 'chatflutter210701',
    storageBucket: 'chatflutter210701.appspot.com',
    iosClientId: '170898355374-1odagil5f4hedqp5u7upk8lo0e60lpqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVYqt1Hh61bPIdtEbNIRBYyojoR_05UHo',
    appId: '1:170898355374:ios:cf37c3962f500380d9a93f',
    messagingSenderId: '170898355374',
    projectId: 'chatflutter210701',
    storageBucket: 'chatflutter210701.appspot.com',
    iosClientId: '170898355374-ulnniq5318li7te0596t476kvf6575mi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
